name: ${project.name}
main: net.daboross.bukkitdev.timedblockreplace.TimedBlockReplacePlugin
version: ${project.version}
author: Dabo Ross
description: |
  TimedBlockReplace allows you to replace blocks after they are placed.
  For instance you can replace cobble with stone 5 minutes after it is placed.
commands:
  tbr:
    description: This is the base command for TimedBlockReplace
    usage: |
      To add a new block that should change:
      /<command> add [from-block] [to-block] [time-till-change]
      To remove a block that should change:
      /<command> remove [from-block]
      To list all blocks that are currently going to change when placed:
      /<command> list
      For command help / to view this:
      /<command> help
    aliases: [timedblockreplace]
